### PR TITLE
Restrict extra fields and improve logic for selecting proper fields to populate profile

### PR DESCRIPTION
**Pull request by ahuang11**
## Summary
Use the __fields__ attribute since it doesn’t have block_type_slug, but contains all the relevant fields to a target config.
image

Also bounds fields allowed in `DbtConfigs` since the field `extras` should be the only way.

## Relevant Issue(s)

Closes https://github.com/PrefectHQ/prefect-dbt/issues/59

## Checklist
- [x] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-dbt/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by desertaxle** [comment]
Is it possible that to have each `DbtConfigs` subclass reimplement `_populate_configs_json`? I'm concerned about the growing complexity of the abstraction we have now and I think that reimplementing config JSON creation on each subclass would make this easier to understand and less coupled.

**Comment by ahuang11** [comment]
Not sure I'm understanding, can you elaborate a bit more on this? I think all subclasses will encounter `block_type_slug` and `_is_anonymous` duplicate

**Comment by desertaxle** [comment]
Yes, but on specific subclasses you should be able to explicitly define which keys should go in the config with `.dict(include={"foo", "bar"})` which I think will be easier to understand and debug.

**Comment by ahuang11** [comment]
I prefer this branch over https://github.com/PrefectHQ/prefect-dbt/pull/61

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
