### PR TITLE
Try token attr fix for compute engine service account

### LINKED ISSUE #92: Manage Compute engine credentials in addition of oauth2
Hi Prefect-dbt team,

Following this tread https://github.com/PrefectHQ/prefect-dbt/issues/56
I tried to authenticate within a kubernetes pod associated to a valid service account.
`google.auth.default()` returns a compute engine credentials https://google-auth.readthedocs.io/en/master/reference/google.auth.compute_engine.credentials.html

Then the code fails because of `'Credentials' object has no attribute 'refresh_token'`
From what I understood the code expects a https://google-auth.readthedocs.io/en/stable/reference/google.oauth2.credentials.html

Would be super nice to be able to use the compute_engine credentials

### PR DESCRIPTION
**Pull request by lucienfregosibodyguard**
Add method + refresh credentials to get the token

[Closes #92](https://github.com/PrefectHQ/prefect-dbt/issues/92)

### Checklist

- [X] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-dbt/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-dbt/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by desertaxle** [comment]
Thanks for the contribution @lucienfregosibodyguard! It looks like some of the tests need to be updated to account for the changes in this PR. Also, would you be able to add an entry to [the changelog](https://github.com/PrefectHQ/prefect-dbt/blob/main/CHANGELOG.md) describing these changes?

**Comment by ahuang11** [comment]
Thanks for looking into this and making a PR! Looking at the changes, I realized we already have a built-in method for this. I think we should call it, but it's currently async so I made it sync compatible [here](https://github.com/PrefectHQ/prefect-gcp/pull/80).

**Comment by lucienfregosibodyguard** [comment]
@ahuang11 it totally makes sense you can close this PR then and use only the original one 

Can't wait to have this merged

**Comment by ahuang11** [comment]
Sure; I'll first merge this PR into mine so you're part of the contributors. Thanks again!

**Pull request merged**
